---
title: "Data Science portfolio Thijmen Weijgertze"
site: bookdown::bookdown_site
data: "2024"
bibliography: References.bib
output: 
    bookdown::gitbook:
        css: css/style.css
        number_sections: false
        anchor_sections: false
        split_by: chapter
        config:
            sharing:
                 github: yes
                 facebook: no
                 twitter: no
                 all: no
            toc:
                collapse: section
                scroll_highlight: yes
                before: <li class="toc"><h2>Table of Contents</h2></li>
                toc_depth: 3
github-repo: "ThijmenWeijgertze/PortofolioBookdown"
description: 'Data Science portfolio for the "Data Science For Biology" course given by the "HU University of Applied Sciences Utrecht written by Thijmen Weijgertze"'
params:
  printCode: TRUE
  printWarning: FALSE
  printMessage: FALSE
  covidData: data/CovidData.csv
  covidYear: 2020
  covidMonth: 4
---

```{r, index setup, include=FALSE}
# set this option in the first code chunk in the document
knitr::opts_chunk$set(
  echo = params$printCode,
  warning = params$printWarning,
  message = params$printMessage
  )
```

# Main Page {#index}

### Introduction 

<p class="justify">This github page is written by Thijmen Weijgertze using Rstudio. I am a 3rd year Life Science student at HU University of Applied Sciences Utrecht. In the past half year I've followed a DataScience minor provided by the HU. This Github page serves as my DataScience portofolio for showing off my DataScience skills. The course is created by @gestelDataScienceWorkflows based on the "bookdown: Authoring Books and Technical Documents with R Markdown" book from @xieBookdownAuthoringBooksa.</p>

### Toc

- [Main Page](#index)
- [Meta Data](#00)
- [Resume](#01)
- [Guerrilla Analytics](#02)
- [C. Elegans plate experiment](#03)
- [Open Peer Review](#04)
- [Predicting breast cancer recurrence events using random forests](#05)
- [Rpackage (twPackage)](#06)
- [Antimicrobial resistance project](#07)
- [Analyzing Covid-19 data using parameters](#08)
- [Appendix 1: COVID-19 Vaccine paper](#19)
- [Session Info](#20)
- [Bibliography](#21)

### Contact information {-}

- [E-mail: thijmen.weijgertze@student.hu.nl](thijmen.weijgertze@student.hu.nl)
- [GitHub: https://github.com/ThijmenWeijgertze](https://github.com/ThijmenWeijgertze)
- [LinkedIn: https://www.linkedin.com/in/thijmen-weijgertze-968a5a265/](https://www.linkedin.com/in/thijmen-weijgertze-968a5a265/)
