
# specify website directory

Website host folder:

```{r}
### specify the folder from where you host the website
websiteFolder <- "../ThijmenWeijgertze-portfolio/"
```

# Upload site

upload host site:

```{r}

### remove files

# Define the directory where the files are located
dir_path <- websiteFolder

# Get a list of all HTML files in the directory
file_list <- list.files(
  path = dir_path, 
  pattern = NULL,
  full.names = TRUE,
  recursive = TRUE
)

# Define the patterns you want to match
patterns <- c("*.html", "*.css", "reference-keys.txt", "libs", ".js", ".png")

# Use regex to match the patterns
file_list <- file_list[grep(paste(patterns, collapse = "|"), file_list)]

# Go over all files and delete them
for (file_path in file_list) {
  if (file.exists(file_path)) {
    file.remove(file_path)
  }
}

paste0("Deleted files")

### remove folders

folderNames <- c(
  paste0(websiteFolder, "libs"), 
  paste0(websiteFolder, "_main_files"),
  paste0(websiteFolder, "data")
)

for (folder in folderNames) {
  if (file.exists(folder)){
  unlink(folder, recursive = TRUE) 
  paste("unlinked: ", folder)
  }
}

paste("Deleted folders")

### copy the _book files

# Function to recursively copy files and directories
recursive_copy <- function(source_dir, destination_dir) {
  files <- list.files(source_dir, full.names = TRUE, recursive = TRUE)
  
  for (file in files) {
    # Get relative path
    relative_path <- tools::file_path_sans_ext(file)
    relative_path <- substr(relative_path, nchar(source_dir) + 2, nchar(relative_path))
    
    # Create destination directory if it doesn't exist
    dest_dir <- file.path(destination_dir, dirname(relative_path))
    if (!dir.exists(dest_dir)) {
      dir.create(dest_dir, recursive = TRUE)
    }
    
    # Copy the file to the destination
    file.copy(file, file.path(destination_dir, relative_path))
  }
}

# Call the function to recursively copy files and directories
recursive_copy("_book", websiteFolder)

paste0("Copied files")
```

